language: go
go:
- stable
before_install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
install:
- dep ensure
before_deploy:
- go get github.com/mitchellh/gox
- mkdir releases
- gox -os='!windows !netbsd !openbsd !darwin !freebsd' -osarch='!linux/mipsle !linux/arm !linux/s390x !linux/mips64le !linux/mips !linux/mips64'
  -output="releases/{{.Dir}}_`git describe --tags --abbrev=0`_{{.OS}}_{{.Arch}}/{{.Dir}}"
  -ldflags "-X main.Version=`git describe --tags --abbrev=0`"
- find releases -maxdepth 2 -mindepth 2 -type f -exec bash -c 'tar -cvzf "$(dirname
  {}).tar.gz" -C "$(dirname {})" $(basename {})' \;
deploy:
  provider: releases
  api_key:
    secure: iNzUF8QKEW7W+W/Aogt7UiwiTXTyZ472R/oLR7RFE2flTSxd1BXR9ZV3k7RvedhN/brFc+cnUFohQtDsRj4VG4+rhxhAOCwJ1uzPwLTQXtd+Pq1TwVV7AHaDdLeSDcHzrVXkWNoNuju9AFN9t+w4SGA5swiA1hC9Sib4HZSsuU3XdvL25g6pK8bPxSyHFWtIKyeqshE+d8+RqNN+1c7zaHIJHaOKep7K3hl3QBmx4L2ibRfE7LMZk+GKioN5cVhn3JCf/t1dUKV87Uwd1AHubCxttQ1r2cVNQ0fdp2LkzPwiwiMkDOU+OHpjtB5HBS4TQgSlo7TXSIw5Pd14iwWfKC/J2qvO/xZ54Ofp0mMjDWvWWBDVJwNWTkmFDbCR1lJ0mNFjmfLfHIWjFH/LgNTPGZYMo87fLAtMoPITwj4M3yuq9DfrtX3zvrVwMHSoYL4eviHTkdksYbkgnouHLMW0HGFGA06BOuQrg9UsyX/j/TuejrmphgIM7TNPz8Sria4KZroLPUhRx6qlFQmKduf8NSZU8Iqtwq7VwmgZAk+WmGh2fAk+DQiw+kT33HTVIMOGPvz6C4aD63JXWIT0zZvh4js7hen9Hbn1r1qyoboBjlsoX9DUW1LnzQfN/Yoz2Q9E5Qemr09LReOzteUZd+rvqZkyaT0jZjhMSDF2BByDG28=
  file: "releases/*.tar.gz"
  file_glob: true # enables wildcards in file names
  skip_cleanup: true
  on:
    repo: splattner/docker-machine-driver-cloudscale
    tags: true
