language: go
go:
- stable
before_install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
install:
- dep ensure
before_deploy:
- go get github.com/mitchellh/gox
- mkdir releases
- gox -osarch='!netbsd/arm !openbsd/386 !openbsd/amd64 !netbsd/386 !netbsd/amd64'
  -output="releases/{{.Dir}}_`git describe --tags --abbrev=0`_{{.OS}}_{{.Arch}}/{{.Dir}}"
  -ldflags "-X main.Version=`git describe --tags --abbrev=0`"
- find releases -maxdepth 2 -mindepth 2 -type f -exec bash -c 'tar -cvzf "$(dirname
  {}).tar.gz" -C "$(dirname {})" $(basename {})' \;
deploy:
  provider: releases
  api_key:
    secure: Z648Ni28BUey9nvaaCxEbhtqlsZ5uNj1pgsiU/VuYIbtUKpK/g4T/58JMdRePp8GaeOBD/td5gRu1U7UFEDLyWV1SWqZaI/KAhEkx9jASZhzNQwg8KLfX4u5Czqw4yxYkBn2POYVc5JtLhEGAgSWgUc8s7wY9j3WIYIcQpnrXLjAtQLYyqDGeAYqc0qoAU5wuL6/xXuNon8QxPygkB1/weEz606q+oQONmgefNgVtjRUKYNm23UYs5Zrr8mkc3+SfFvXG6tfWoCU1iO9N5laA1g+Sh0OyjcUqMs9APczFhXn8CnTaCiGsEYs8vfRTcxyo/DWw9NG9yhZq8cdLDcneWtdKPliVNSqUsls17Rq8LF5+dKlEAKPXIAFpFl/aIC74H7LPiTmx0QqJ/JM3D4pUarfhdBv3CioCMKhz03zLBuLckHK9PziUMjIxsb3B/VM6w6QGpUyzCPNXFIE9Laq+WxOrDgcwkzkVM5QwfuoyjOLeRs99upuVLIftYicsJ0PjzudgFI7AXa2nfptgCUjXL7vtbMDr7sWAZGurgGaRgp4B1oPAvlW9eSC65qhPmh/zv7vWNXxnm0Ev/OUQrnmvt4Oh1523WHq2473ksO6GcunCWVxUsXqWbNlc32zV1YjZGDdxys/UjviyarnLBwxii4ydTNXKO36sZtyVkeiGzI=
  file: "releases/*.tar.gz"
  skip_cleanup: true
  on:
    repo: splattner/docker-machine-driver-cloudscale
    tags: true
